import { ClientCompany, NotificationItem } from "./types";

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  { id: "n1", type: "overdue", companyName: "หจก. รุ่งเรืองก่อสร้าง", message: "เลยกำหนด 4 วัน ยังขาด 4 รายการ", time: "29 พ.ค. 09:00", isRead: false },
  { id: "n2", type: "overdue", companyName: "หจก. ครัวคุณยาย", message: "เลยกำหนด ส่งเพียง 1/4", time: "29 พ.ค. 09:00", isRead: false },
  { id: "n3", type: "alert", companyName: "บจก. ไทยเฮิร์บ คอสเมติก", message: "ส่งลิงก์ขอเอกสารให้ลูกค้า", time: "29 พ.ค. 11:00", isRead: true },
  { id: "n4", type: "reject", companyName: "บจก. ช้อปปี้เดย์ ออนไลน์", message: "ตีกลับ \"ใบกำกับภาษีซื้อ\" (ภาพเบลอ)", time: "28 พ.ค. 16:30", isRead: true },
  { id: "n5", type: "upload", companyName: "บจก. ช้อปปี้เดย์ ออนไลน์", message: "อัปโหลด \"ใบกำกับภาษีขาย\"", time: "28 พ.ค. 16:10", isRead: true },
  { id: "n6", type: "success", companyName: "บจก. ลีลาวดี คลินิกเวชกรรม", message: "ส่งเอกสารครบ รอตรวจ", time: "27 พ.ค. 10:24", isRead: true },
  { id: "n7", type: "success", companyName: "บจก. กรีนการ์เด้น คาเฟ่", message: "ตรวจเอกสารเสร็จ", time: "23 พ.ค. 14:05", isRead: true },
  { id: "n8", type: "warning", companyName: "บจก. เอเชีย อิมพอร์ต เอ็กซ์พอร์ต", message: "ใกล้ครบกำหนด (เหลือ 4 วัน)", time: "28 พ.ค. 08:00", isRead: true },
];

export const MOCK_COMPANIES: ClientCompany[] = [
  {
    id: "c1",
    name: "บจก. กรีนการ์เด้น คาเฟ่",
    industry: "คาเฟ่",
    package: "Starter",
    status: "ส่งครบ-ตรวจแล้ว",
    docsSubmitted: 6,
    totalDocs: 6,
    deadline: "25 พ.ค.",
    accountManager: "ศุภวัฒน์",
    contactName: "คุณมานี ใจดี (เจ้าของ)",
    contactPhone: "081-111-2233",
    contactLineId: "@client01",
    note: "ส่งตรงเวลาประจำ",
    docs: [
      { id: "d1_1", category: "ใบกำกับภาษีขาย", status: "ตรวจแล้ว", fileName: "ขาย_2569-04-001.pdf", fileSize: "1.2 MB", uploadedAt: "22 พ.ค." },
      { id: "d1_2", category: "ใบกำกับภาษีซื้อ", status: "ตรวจแล้ว", fileName: "ซื้อ_2569-04-001.pd", fileSize: "2.4 MB", uploadedAt: "22 พ.ค." },
      { id: "d1_3", category: "Statement ธนาคาร", status: "ตรวจแล้ว", fileName: "Stmt_Apr.pdf", fileSize: "5.1 MB", uploadedAt: "22 พ.ค." },
      { id: "d1_4", category: "บิลค่าใช้จ่าย", status: "ตรวจแล้ว", fileName: "Exp_Apr.zip", fileSize: "8.0 MB", uploadedAt: "22 พ.ค." },
      { id: "d1_5", category: "เงินเดือนพนักงาน", status: "ตรวจแล้ว", fileName: "PR_Apr.pdf", fileSize: "0.5 MB", uploadedAt: "22 พ.ค." },
      { id: "d1_6", category: "เอกสารอื่นๆ", status: "ตรวจแล้ว", fileName: "Other.pdf", fileSize: "1.1 MB", uploadedAt: "22 พ.ค." },
    ]
  },
  {
    id: "c2",
    name: "บจก. สมาร์ทเทค โซลูชันส์",
    industry: "ไอที",
    package: "Pro",
    status: "กำลังส่ง",
    docsSubmitted: 4,
    totalDocs: 6,
    deadline: "31 พ.ค.",
    accountManager: "ณัฐพร",
    contactName: "คุณวิชัย รุ่งโรจน์ (ผจก.)",
    contactPhone: "082-222-3344",
    contactLineId: "@client02",
    note: "-",
    docs: [
      { id: "d2_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย_2569-04-001.pdf", fileSize: "1.0 MB", uploadedAt: "28 พ.ค." },
      { id: "d2_2", category: "ใบกำกับภาษีซื้อ", status: "รับแล้ว", fileName: "ซื้อ_2569-04-001.pdf", fileSize: "1.5 MB", uploadedAt: "28 พ.ค." },
      { id: "d2_3", category: "Statement ธนาคาร", status: "รอ" },
      { id: "d2_4", category: "บิลค่าใช้จ่าย", status: "รับแล้ว", fileName: "Exp_Apr.pdf", fileSize: "3.2 MB", uploadedAt: "28 พ.ค." },
      { id: "d2_5", category: "เงินเดือนพนักงาน", status: "รอ" },
      { id: "d2_6", category: "เอกสารอื่นๆ", status: "รับแล้ว", fileName: "Misc.pdf", fileSize: "0.8 MB", uploadedAt: "28 พ.ค." },
    ]
  },
  {
    id: "c3",
    name: "หจก. รุ่งเรืองก่อสร้าง",
    industry: "รับเหมาก่อสร้าง",
    package: "Growth",
    status: "เลยกำหนด",
    docsSubmitted: 2,
    totalDocs: 6,
    deadline: "25 พ.ค.",
    accountManager: "ณัฐพร",
    contactName: "คุณสมศักดิ์ มั่นคง",
    contactPhone: "083-333-4455",
    contactLineId: "@client03",
    note: "เลทประจำ โทรอย่าแชท",
    docs: [
      { id: "d3_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย_2569-04-001.pdf", fileSize: "2.1 MB", uploadedAt: "24 พ.ค." },
      { id: "d3_2", category: "ใบกำกับภาษีซื้อ", status: "รอ" },
      { id: "d3_3", category: "Statement ธนาคาร", status: "รับแล้ว", fileName: "Stmt_Apr.pdf", fileSize: "1.1 MB", uploadedAt: "24 พ.ค." },
      { id: "d3_4", category: "บิลค่าใช้จ่าย", status: "รอ" },
      { id: "d3_5", category: "เงินเดือนพนักงาน", status: "รอ" },
      { id: "d3_6", category: "เอกสารอื่นๆ", status: "รอ" },
    ]
  },
  {
    id: "c4",
    name: "บจก. ลีลาวดี คลินิกเวชกรรม",
    industry: "คลินิกความงาม",
    package: "Growth",
    status: "ส่งครบ-รอตรวจ",
    docsSubmitted: 6,
    totalDocs: 6,
    deadline: "28 พ.ค.",
    accountManager: "ศุภวัฒน์",
    contactName: "พญ.พิมพ์ใจ งาม",
    contactPhone: "084-444-5566",
    contactLineId: "@client04",
    note: "-",
    docs: [
      { id: "d4_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย.pdf", fileSize: "1.2 MB", uploadedAt: "27 พ.ค." },
      { id: "d4_2", category: "ใบกำกับภาษีซื้อ", status: "รับแล้ว", fileName: "ซื้อ.pdf", fileSize: "1.5 MB", uploadedAt: "27 พ.ค." },
      { id: "d4_3", category: "Statement ธนาคาร", status: "รับแล้ว", fileName: "Stmt.pdf", fileSize: "2.0 MB", uploadedAt: "27 พ.ค." },
      { id: "d4_4", category: "บิลค่าใช้จ่าย", status: "รับแล้ว", fileName: "Exp.pdf", fileSize: "4.1 MB", uploadedAt: "27 พ.ค." },
      { id: "d4_5", category: "เงินเดือนพนักงาน", status: "รับแล้ว", fileName: "PR.pdf", fileSize: "0.5 MB", uploadedAt: "27 พ.ค." },
      { id: "d4_6", category: "เอกสารอื่นๆ", status: "รับแล้ว", fileName: "Other.pdf", fileSize: "1.0 MB", uploadedAt: "27 พ.ค." },
    ]
  },
  {
    id: "c5",
    name: "บจก. ช้อปปี้เดย์ ออนไลน์",
    industry: "E-commerce",
    package: "Growth",
    status: "กำลังส่ง",
    docsSubmitted: 5,
    totalDocs: 6,
    deadline: "31 พ.ค.",
    accountManager: "ศุภวัฒน์",
    contactName: "คุณนัท ขายดี",
    contactPhone: "085-555-6677",
    contactLineId: "@client05",
    note: "-",
    docs: [
      { id: "d5_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย_2569-04-001.pdf", fileSize: "3.2 MB", uploadedAt: "28 พ.ค." },
      { id: "d5_2", category: "ใบกำกับภาษีซื้อ", status: "ตีกลับ", fileName: "IMG_2931.jpg", fileSize: "0.8 MB", uploadedAt: "28 พ.ค.", rejectionReason: "ภาพเบลอ อ่านเลขใบกำกับไม่ออก" },
      { id: "d5_3", category: "Statement ธนาคาร", status: "รับแล้ว", fileName: "Stmt_Apr.pdf", fileSize: "1.5 MB", uploadedAt: "28 พ.ค." },
      { id: "d5_4", category: "บิลค่าใช้จ่าย", status: "รับแล้ว", fileName: "Exp_Apr.pdf", fileSize: "4.2 MB", uploadedAt: "28 พ.ค." },
      { id: "d5_5", category: "เงินเดือนพนักงาน", status: "รับแล้ว", fileName: "PR_Apr.pdf", fileSize: "0.5 MB", uploadedAt: "28 พ.ค." },
      { id: "d5_6", category: "เอกสารอื่นๆ", status: "รับแล้ว", fileName: "Misc.pdf", fileSize: "1.1 MB", uploadedAt: "28 พ.ค." },
    ]
  },
  {
    id: "c6",
    name: "บจก. บ้านสวยพร็อพเพอร์ตี้",
    industry: "อสังหาฯ",
    package: "Pro",
    status: "ส่งครบ-ตรวจแล้ว",
    docsSubmitted: 6,
    totalDocs: 6,
    deadline: "20 พ.ค.",
    accountManager: "ณัฐพร",
    contactName: "คุณกานต์ ทรัพย์เพิ่ม",
    contactPhone: "086-666-7788",
    contactLineId: "@client06",
    note: "ส่งเร็วเสมอ",
    docs: [
      { id: "d6_1", category: "ใบกำกับภาษีขาย", status: "ตรวจแล้ว", fileName: "ขาย.pdf", fileSize: "1.1 MB", uploadedAt: "18 พ.ค." },
      { id: "d6_2", category: "ใบกำกับภาษีซื้อ", status: "ตรวจแล้ว", fileName: "ซื้อ.pdf", fileSize: "1.2 MB", uploadedAt: "18 พ.ค." },
      { id: "d6_3", category: "Statement ธนาคาร", status: "ตรวจแล้ว", fileName: "Stmt.pdf", fileSize: "2.5 MB", uploadedAt: "18 พ.ค." },
      { id: "d6_4", category: "บิลค่าใช้จ่าย", status: "ตรวจแล้ว", fileName: "Exp.pdf", fileSize: "3.2 MB", uploadedAt: "18 พ.ค." },
      { id: "d6_5", category: "เงินเดือนพนักงาน", status: "ตรวจแล้ว", fileName: "PR.pdf", fileSize: "0.5 MB", uploadedAt: "18 พ.ค." },
      { id: "d6_6", category: "เอกสารอื่นๆ", status: "ตรวจแล้ว", fileName: "Other.pdf", fileSize: "1.0 MB", uploadedAt: "18 พ.ค." },
    ]
  },
  {
    id: "c7",
    name: "หจก. ครัวคุณยาย",
    industry: "ร้านอาหาร",
    package: "Starter",
    status: "เลยกำหนด",
    docsSubmitted: 1,
    totalDocs: 4,
    deadline: "25 พ.ค.",
    accountManager: "ศุภวัฒน์",
    contactName: "คุณฝน (หลานสาว)",
    contactPhone: "087-777-8899",
    contactLineId: "@client07",
    note: "ส่งช้าประจำ ต้องตามหลายรอบ",
    docs: [
      { id: "d7_1", category: "บิลขาย", status: "รับแล้ว", fileName: "ขาย.pdf", fileSize: "1.5 MB", uploadedAt: "24 พ.ค." },
      { id: "d7_2", category: "บิลซื้อ", status: "รอ" },
      { id: "d7_3", category: "Statement ธนาคาร", status: "รอ" },
      { id: "d7_4", category: "เอกสารอื่นๆ", status: "รอ" },
    ]
  },
  {
    id: "c8",
    name: "บจก. เอเชีย อิมพอร์ต เอ็กซ์พอร์ต",
    industry: "นำเข้า-ส่งออก",
    package: "Pro",
    status: "กำลังส่ง",
    docsSubmitted: 3,
    totalDocs: 6,
    deadline: "2 มิ.ย.",
    accountManager: "ณัฐพร",
    contactName: "คุณเดวิด เฉิน",
    contactPhone: "088-888-9900",
    contactLineId: "@client08",
    note: "-",
    docs: [
      { id: "d8_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย.pdf", fileSize: "2.1 MB", uploadedAt: "28 พ.ค." },
      { id: "d8_2", category: "ใบกำกับภาษีซื้อ", status: "รับแล้ว", fileName: "ซื้อ.pdf", fileSize: "1.8 MB", uploadedAt: "28 พ.ค." },
      { id: "d8_3", category: "Statement ธนาคาร", status: "รับแล้ว", fileName: "Stmt.pdf", fileSize: "3.5 MB", uploadedAt: "28 พ.ค." },
      { id: "d8_4", category: "บิลค่าใช้จ่าย", status: "รอ" },
      { id: "d8_5", category: "เงินเดือนพนักงาน", status: "รอ" },
      { id: "d8_6", category: "เอกสารอื่นๆ", status: "รอ" },
    ]
  },
  {
    id: "c9",
    name: "บจก. ครีเอทีฟ มีเดีย เอเจนซี",
    industry: "เอเจนซีโฆษณา",
    package: "Growth",
    status: "ส่งครบ-รอตรวจ",
    docsSubmitted: 6,
    totalDocs: 6,
    deadline: "28 พ.ค.",
    accountManager: "ศุภวัฒน์",
    contactName: "คุณบีม สร้างสรรค์",
    contactPhone: "089-999-0011",
    contactLineId: "@client09",
    note: "-",
    docs: [
      { id: "d9_1", category: "ใบกำกับภาษีขาย", status: "รับแล้ว", fileName: "ขาย.pdf", fileSize: "1.1 MB", uploadedAt: "26 พ.ค." },
      { id: "d9_2", category: "ใบกำกับภาษีซื้อ", status: "รับแล้ว", fileName: "ซื้อ.pdf", fileSize: "1.5 MB", uploadedAt: "26 พ.ค." },
      { id: "d9_3", category: "Statement ธนาคาร", status: "รับแล้ว", fileName: "Stmt.pdf", fileSize: "2.2 MB", uploadedAt: "26 พ.ค." },
      { id: "d9_4", category: "บิลค่าใช้จ่าย", status: "รับแล้ว", fileName: "Exp.pdf", fileSize: "4.0 MB", uploadedAt: "26 พ.ค." },
      { id: "d9_5", category: "เงินเดือนพนักงาน", status: "รับแล้ว", fileName: "PR.pdf", fileSize: "0.5 MB", uploadedAt: "26 พ.ค." },
      { id: "d9_6", category: "เอกสารอื่นๆ", status: "รับแล้ว", fileName: "Other.pdf", fileSize: "1.0 MB", uploadedAt: "26 พ.ค." },
    ]
  },
  {
    id: "c10",
    name: "บจก. ไทยเฮิร์บ คอสเมติก",
    industry: "โรงงานเครื่องสำอาง",
    package: "Growth",
    status: "ยังไม่เริ่ม",
    docsSubmitted: 0,
    totalDocs: 6,
    deadline: "5 มิ.ย.",
    accountManager: "ณัฐพร",
    contactName: "คุณอรวรรณ หอมหวล",
    contactPhone: "090-000-1122",
    contactLineId: "@client10",
    note: "ลูกค้าใหม่",
    docs: [
      { id: "d10_1", category: "ใบกำกับภาษีขาย", status: "รอ" },
      { id: "d10_2", category: "ใบกำกับภาษีซื้อ", status: "รอ" },
      { id: "d10_3", category: "Statement ธนาคาร", status: "รอ" },
      { id: "d10_4", category: "บิลค่าใช้จ่าย", status: "รอ" },
      { id: "d10_5", category: "เงินเดือนพนักงาน", status: "รอ" },
      { id: "d10_6", category: "เอกสารอื่นๆ", status: "รอ" },
    ]
  }
];
